[build]
  publish = "framer_blog_converter"
  command = "pip install -r framer_blog_converter/requirements.txt"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  FLASK_ENV = "production"

[context.deploy-preview.environment]
  FLASK_ENV = "preview"

[context.branch-deploy.environment]
  FLASK_ENV = "development"
