services:
  - type: web
    name: framer-blog-converter
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
